### PR TITLE
Bug Fix: Resume training from checkpoints

### PR DESCRIPTION
**Pull request by KKcorps**
Currently the model tries to load all the weights from the checkpoint and fails. 

This is because we only save the adapter weights and not the full model weights.

The PR aims to fix this issue. 

Also use #44 to correctly save the weights.

The fix has been borrowed from https://github.com/vihangd/alpaca-qlora/blob/b243010623dc213e1a4bae98c247f215ec0a2704/finetune.py#L259

### CODE REVIEW

**Comment by KKcorps** [comment]
I should honestly refactor the variable names but for now it works. `resume_from_checkpoint` is probably not needed, just need to check if `checkpoint_dir` is used someplace else or we can simply reuse that

**Comment by Glavin001** [comment]
Confirmed, I had this problem, too:

```
base_model.model.model.layers.31.mlp.up_proj.lora_A.default.weight tensor(5.1447, device='cuda:0')
base_model.model.model.layers.31.mlp.up_proj.lora_B.default.weight tensor(0.6571, device='cuda:0')
trainable params: 0.0 || all params: 3660320768 || trainable: 0.0
loaded model
Using pad_token, but it is not set yet.
Found cached dataset json (/home/ubuntu/.cache/huggingface/datasets/json/edie-v1-aeae2d6cb09a3130/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 776.36it/s]
Loading cached processed dataset at /home/ubuntu/.cache/huggingface/datasets/json/edie-v1-aeae2d6cb09a3130/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4/cache-3a38f878dec0519d.arrow
Loading cached processed dataset at /home/ubuntu/.cache/huggingface/datasets/json/edie-v1-aeae2d6cb09a3130/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4/cache-aec09cee3643a729.arrow
torch.float32 422326272 0.11537932153507864
torch.uint8 3238002688 0.8846206784649213
Traceback (most recent call last):
  File "/workspace/./scripts/qlora.py", line 822, in <module>
    train()
  File "/workspace/./scripts/qlora.py", line 779, in train
    train_result = trainer.train(resume_from_checkpoint=checkpoint_dir)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/transformers/trainer.py", line 1685, in train
    self._load_from_checkpoint(resume_from_checkpoint)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/transformers/trainer.py", line 2160, in _load_from_checkpoint
    raise ValueError(f"Can't find a valid checkpoint at {resume_from_checkpoint}")
ValueError: Can't find a valid checkpoint at ./output-edie-v1.0.4/checkpoint-20
```

Applying this patch fixed it. 🎉  Thank you!

**Comment by artidoro** [comment]
Hey @KKcorps, thank you for your contributions to QLoRA! 
This fix looks good! However, does it also reload the optimizer and scheduler states? That would be important to resume a training run.

I agree with your refactoring suggestions.

**Comment by KKcorps** [comment]
@artidoro you are correct it doesn't reload the optimizer and scheduler states. Checking if hugging face allows that seperately, otherwise we might have to just load the full checkpoint.

For loading the full checkpoint, we would also need `pytorch_model.bin` which we delete currently

**Comment by artidoro** [comment]
Merging from now as it solves one problem. Will tackle the second in a separate PR.

**Review by artidoro — APPROVED** [review]

**Comment by Thytu** [comment]
It appears that this error still occurs even after the merge.

Receiving `ValueError: Can't find a valid checkpoint at {MODEL_NAME}/checkpoint-{INT}` every time I try to resume from checkpoint (while being synch on main)

**Pull request merged**
